import os
import subprocess
import time

def send_notification(title: str, message: str, sound: str = "Basso"):
    """
    Sends a macOS native system notification.
    """
    try:
        script = f'display notification "{message}" with title "{title}" sound name "{sound}"'
        subprocess.run(["osascript", "-e", script], check=False)
    except Exception as e:
        print(f"⚠️ Failed to send notification: {e}")

def trigger_red_light(error_msg: str):
    """
    Generates a professional 'Field Report' (Markdown) to notify the user of Auth requirements.
    Replaces the previous 'Red Light' HTML approach.
    """
    user_desktop = os.path.expanduser("~/Desktop")
    # Use a professional filename
    alert_file = os.path.join(user_desktop, "🔔_STATUS_REPORT_AUTH_REQUIRED.md")
    
    current_time = time.strftime("%Y-%m-%d %H:%M:%S")
    
    md_content = f"""# 🐿️ FlashSquirrel Field Report: Authentication Required
> **Status**: ⏸️ **PAUSED** (Awaiting Credentials)
> **Time**: {current_time}

## 📋 Situation Summary
The automated research unit has encountered a security gatekeeper at the **NotebookLM Library**.
To maintain "Human-Like" behavior and avoid detection, the system requires a manual badge renewal (Cookie Refresh).

> **Reason**: {error_msg}

## 🛠️ Recommended Action
Please perform the standardized maintenance ritual to restore full automation.

1.  Open your terminal.
2.  Run the following command:
    ```bash
    python3 {os.path.join(os.path.dirname(os.path.abspath(__file__)), 'login_wizard.py')}
    ```
3.  Follow the on-screen prompt to log in once.

*This report was automatically generated by the FlashSquirrel Watchdog.*
"""
    
    try:
        with open(alert_file, "w", encoding="utf-8") as f:
            f.write(md_content)
        
        # Open the Markdown file responsibly (Cross-Platform)
        if sys.platform == "darwin":
            subprocess.run(["open", alert_file], check=False)
            send_notification("System Status Update", "Authentication Refresh Required. See Report.", "Hero")
        elif sys.platform == "win32":
            os.startfile(alert_file)
            print("🔔 Windows Notification: Authentication Refresh Required. Check the report on your Desktop.")
        else:
            # Linux/Other
            try:
                subprocess.run(["xdg-open", alert_file], check=False)
            except:
                print(f"Please open: {alert_file}")
            
        print(f"📝 STATUS REPORT GENERATED: {alert_file}")
        
    except Exception as e:
        print(f"⚠️ Failed to generate Status Report: {e}")

if __name__ == "__main__":
    # Test
    trigger_red_light("Session Cookie Expired (Normal Rotation)")
